version: "3.2"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./mariadb.env
    environment:
      - TIMEZONE=Europe/Madrid
    restart: always

#GLPI Container
  glpi:
    image: ubuntu-glpi:ubuntu-glpi
    container_name : glpi10
    hostname: glpi10
    ports:
      - "8081:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./www:/var/www
      - ./files:/var/lib/glpi
      - ./config:/var/etc/glpi
    env_file:
      - ./mariadb.env
    environment:
      - TIMEZONE=Europe/Madrid
      - ID_ADMINER=00001
    restart: always