version: "3.2"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    #TO-DO change host and container name
    container_name: mariadb-test
    hostname: mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - ./mariadb.env
    environment:
      - TIMEZONE=Europe/Madrid
    restart: always

#GLPI Container
  glpi:
    image: ubuntu-glpi:ubuntu-glpi
    #TO-DO change host and container name
    container_name : glpi10-test
    hostname: glpi10
    ports:
      - "8082:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/www:/var/www
      - ./data/files:/var/lib/glpi
      - ./data/config:/etc/glpi
    env_file:
      - ./mariadb.env
    environment:
      - TIMEZONE=Europe/Madrid
      - ID_ADMINER=00001
      - VERSION_GLPI=10.0.7
    restart: always

